# Generated by Django 3.1 on 2021-01-31 15:53

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('instruction', models.TextField()),
                ('duration', models.DurationField(default=datetime.timedelta)),
                ('startTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('passingPercent', models.FloatField(default=40, validators=[django.core.validators.MaxValueValidator(100)])),
                ('negativePercentage', models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('paidExam', models.BooleanField(default=True)),
                ('totalQuestion', models.IntegerField(default=0)),
                ('totalMark', models.FloatField(default=100)),
                ('isManual', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgFile', models.ImageField(null=True, upload_to='quesImg')),
                ('statement', models.TextField()),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('option3', models.TextField(blank=True)),
                ('option4', models.TextField(blank=True)),
                ('hint', models.TextField(blank=True)),
                ('estimatedTime', models.DurationField(default=datetime.timedelta)),
                ('trueFalse', models.BooleanField(default=False)),
                ('fillBlank', models.BooleanField(default=False)),
                ('correctAnswer', models.IntegerField(choices=[(1, 'option1'), (2, 'option2'), (3, 'option3'), (4, 'option4')], default=1)),
                ('explanation', models.TextField(blank=True)),
                ('markPerQues', models.FloatField(default=1.0)),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.difficulty')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='exam.exam')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.level')),
                ('questionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.questiontype')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.subject')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='examType',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exam.examtype'),
        ),
        migrations.AddField(
            model_name='exam',
            name='package',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='package.package'),
        ),
        migrations.CreateModel(
            name='UserExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shuffleId', models.IntegerField(default=0)),
                ('examDate', models.DateField(default=datetime.date.today)),
                ('obtainedMarks', models.FloatField()),
                ('examId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('examId', 'userId')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providedAnswer', models.CharField(max_length=50)),
                ('examId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('examId', 'userId', 'questionId')},
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
            ],
            options={
                'unique_together': {('examId', 'questionId')},
            },
        ),
    ]
