# Generated by Django 3.1 on 2021-02-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='imgFile',
            field=models.ImageField(blank=True, null=True, upload_to='quesImg'),
        ),
    ]
