# Generated by Django 3.1 on 2021-02-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20210206_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexam',
            name='totalCorrectedQuestions',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
