# Generated by Django 3.1 on 2021-02-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_userexam_totalcorrectedquestions'),
        ('exam', '0002_auto_20210205_0140'),
    ]

    operations = [
    ]
