# Generated by Django 3.1 on 2021-02-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_userexam_viewable'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexam',
            name='participationCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userexam',
            name='retakeAble',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
