# Generated by Django 3.1 on 2021-02-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20210217_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexam',
            name='consumedTime',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='userexam',
            name='obtainedMarks',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userexam',
            name='retakeAble',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='userexam',
            name='totalCorrectedQuestions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userexam',
            name='viewAble',
            field=models.BooleanField(),
        ),
    ]
