# Generated by Django 3.1 on 2021-02-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_auto_20210221_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexam',
            name='consumedTime',
            field=models.DurationField(null=True),
        ),
    ]
