# Generated by Django 3.1 on 2021-03-19 15:00

from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0014_userexam_totalincorrectedquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRange', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('viewCount', models.IntegerField(default=0)),
                ('reviseCount', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('exam', 'user', 'dateRange')},
            },
        ),
    ]
