# Generated by Django 3.1 on 2021-03-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_auto_20210319_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexamperformance',
            old_name='reviseCount',
            new_name='retakeCount',
        ),
    ]
