# Generated by Django 3.1 on 2021-04-28 08:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_auto_20210321_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='examType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.examtype'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='startTime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
