# Generated by Django 3.1 on 2021-01-31 15:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('durationDays', models.DurationField(default=datetime.timedelta(days=30))),
                ('fee', models.FloatField()),
                ('isPaid', models.BooleanField(default=False)),
                ('examCount', models.IntegerField()),
                ('titleImageUrl', models.ImageField(blank=True, null=True, upload_to='packageImage')),
            ],
        ),
        migrations.CreateModel(
            name='User_Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('isActive', models.BooleanField(default=False)),
                ('availableExam', models.IntegerField()),
                ('isPinned', models.BooleanField(default=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('package', 'user')},
            },
        ),
    ]
