# Generated by Django 3.1 on 2021-01-31 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='isPaid',
        ),
    ]
