# [START django_app]
runtime: python38
#entrypoint: gunicorn -b :$PORT backend.wsgi

# Update with Redis instance details
env_variables:
  REDISHOST: '10.195.114.11'
  REDISPORT: '6379'

# Update with Serverless VPC Access connector details
vpc_access_connector:
  name: 'projects/exms-302404/locations/asia-southeast2/connectors/my-vpc'

handlers:
# This configures Google App Engine to serve the files in the app's
# static directory.
- url: /static
  static_dir: static/
# This handler routes all requests not caught above to the main app. 
# It is required when static routes are defined, but can be omitted 
# (along with the entire handlers section) when there are no static 
# files defined.
- url: /.*
  script: auto
# [END django_app]