# Generated by Django 3.1 on 2021-02-13 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsFeed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeedCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsFeed.newsfeed')),
            ],
        ),
    ]
