# Generated by Django 3.1 on 2021-02-17 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsFeed', '0006_auto_20210214_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeedCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.IntegerField()),
                ('image2', models.IntegerField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='newsFeed.newsfeed')),
            ],
        ),
    ]
