# Generated by Django 3.1 on 2021-02-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsFeed', '0007_newsfeedcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeedcount',
            name='image',
            field=models.ImageField(upload_to='quesImg'),
        ),
        migrations.AlterField(
            model_name='newsfeedcount',
            name='image2',
            field=models.ImageField(upload_to='quesImg'),
        ),
    ]
