# Generated by Django 3.1 on 2021-02-17 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsFeed', '0008_auto_20210217_1445'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsFeedCount',
        ),
    ]
