# Generated by Django 3.1 on 2021-02-21 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsFeed', '0009_delete_newsfeedcount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsfeed',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_newsfeed.newsfeed_set+', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='ContestNews',
            fields=[
                ('newsfeed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='newsFeed.newsfeed')),
                ('contestWinnerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('newsFeed.newsfeed',),
        ),
    ]
