# Generated by Django 3.1 on 2021-03-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsFeed', '0010_auto_20210221_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestnews',
            name='winnerAnnounceTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
