# Generated by Django 3.1 on 2021-04-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenkeys',
            options={'verbose_name_plural': 'TokenKeys'},
        ),
        migrations.AlterField(
            model_name='tokenkeys',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
