# Generated by Django 3.1 on 2021-03-21 04:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('countryCode', models.CharField(max_length=255)),
                ('defaultCurrency', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userInfo.countries')),
            ],
            options={
                'verbose_name_plural': 'Division',
            },
        ),
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'PostOffice',
            },
        ),
        migrations.CreateModel(
            name='Thana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userInfo.districts')),
            ],
            options={
                'verbose_name_plural': 'Thana',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('thana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userInfo.thana')),
            ],
            options={
                'verbose_name_plural': 'Village',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialName', models.CharField(max_length=255)),
                ('socialUrl', models.CharField(max_length=255)),
                ('socialIcon', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Socials',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profilePics')),
                ('dateOfBirth', models.DateField(null=True)),
                ('bloodGroup', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=191)),
                ('firstName', models.CharField(blank=True, max_length=255, null=True)),
                ('lastName', models.CharField(blank=True, max_length=255, null=True)),
                ('birthId', models.CharField(blank=True, max_length=255, null=True)),
                ('nationalId', models.CharField(blank=True, max_length=255, null=True)),
                ('taxId', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.CharField(blank=True, max_length=255, null=True)),
                ('religion', models.IntegerField(choices=[(1, 'Islam'), (2, 'Christianity'), (3, 'Hinduism'), (4, 'Buddhism'), (5, 'Other')], null=True)),
                ('roadNo', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userInfo.countries')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userInfo.districts')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userInfo.division')),
                ('postOffice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userInfo.postoffice')),
                ('thana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userInfo.thana')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userInfo.village')),
            ],
        ),
        migrations.AddField(
            model_name='postoffice',
            name='thana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userInfo.thana'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.SmallIntegerField(default=0)),
                ('createdAt', models.DateField(default=datetime.date.today)),
                ('updatedAt', models.DateField(default=datetime.date.today)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='districts',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userInfo.division'),
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('sign', models.CharField(max_length=255)),
                ('usdConversionAmount', models.IntegerField()),
                ('expiredAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=5000)),
                ('createdAt', models.DateField(default=datetime.date.today)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organizationName', models.CharField(max_length=255)),
                ('domainName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('metaTitle', models.TextField()),
                ('metaDesc', models.TextField()),
                ('timezone', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=255)),
                ('sms', models.BooleanField(default=False)),
                ('emailNotification', models.BooleanField(default=False)),
                ('guestLogin', models.BooleanField(default=False)),
                ('frontEnd', models.BooleanField(default=False)),
                ('slides', models.SmallIntegerField()),
                ('translate', models.SmallIntegerField(default=0)),
                ('paidExam', models.SmallIntegerField(default=1)),
                ('leaderBoard', models.BooleanField(default=True)),
                ('contact', models.TextField()),
                ('photo', models.CharField(max_length=100)),
                ('createdAt', models.DateField(default=datetime.date.today)),
                ('modifiedAt', models.DateField(default=datetime.date.today)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('createdAT', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userInfo.countries')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
