# Generated by Django 3.1 on 2021-03-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0002_useremail_usermobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermobile',
            name='mobile',
            field=models.CharField(max_length=14),
        ),
    ]
