# Generated by Django 3.1 on 2021-03-31 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userInfo', '0005_auto_20210331_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SpouseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spouseName', models.CharField(blank=True, max_length=254)),
                ('spouseJob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userInfo.profession')),
                ('spouseNationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userInfo.nationality')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MotherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motherName', models.CharField(blank=True, max_length=254)),
                ('motherJob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userInfo.profession')),
                ('motherNationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userInfo.nationality')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FatherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatherName', models.CharField(blank=True, max_length=254)),
                ('fatherJob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userInfo.profession')),
                ('fatherNationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userInfo.nationality')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
