# Generated by Django 3.1 on 2021-04-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0006_fatherinfo_motherinfo_nationality_profession_spouseinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='useremail',
            unique_together=set(),
        ),
    ]
