# Generated by Django 3.1 on 2021-04-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0008_auto_20210401_1713'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermobile',
            unique_together=set(),
        ),
    ]
