# Generated by Django 3.1 on 2021-04-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0010_profile_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='citizenshipStatus',
            field=models.IntegerField(choices=[(1, 'BIRTH'), (2, 'PARENTAGE'), (3, 'MIGRATION'), (4, 'NATURALIZATION'), (5, 'OTHERS')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dualCitizenship',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
