# Generated by Django 3.1 on 2021-04-05 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userInfo', '0011_auto_20210403_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='division',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='postOffice',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='roadNo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='thana',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='village',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadNo', models.CharField(blank=True, max_length=255, null=True)),
                ('isPermanentAddress', models.BooleanField()),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userInfo.countries')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userInfo.districts')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userInfo.division')),
                ('postOffice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userInfo.postoffice')),
                ('thana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userInfo.thana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userInfo.village')),
            ],
        ),
    ]
