# Generated by Django 3.1 on 2021-04-05 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userInfo', '0011_auto_20210403_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='EducationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(blank=True, max_length=254)),
                ('degree', models.IntegerField(choices=[(1, 'PRIMARY'), (2, 'SSC'), (3, 'HSC'), (4, 'BACHELOR'), (5, 'MASTERS'), (6, 'OTHERS')])),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userInfo.fieldofstudy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
