# Generated by Django 3.1 on 2021-04-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0012_educationinfo_fieldofstudy'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationinfo',
            name='activites',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='educationinfo',
            name='completeness',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationinfo',
            name='currentStudent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationinfo',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='educationinfo',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='educationinfo',
            name='grade',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='educationinfo',
            name='startDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='field',
            field=models.CharField(blank=True, default='', max_length=254),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FieldOfStudy',
        ),
    ]
