# Generated by Django 3.1 on 2021-04-05 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0012_auto_20210405_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userInfo.countries'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userInfo.districts'),
        ),
        migrations.AlterField(
            model_name='address',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userInfo.division'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postOffice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userInfo.postoffice'),
        ),
        migrations.AlterField(
            model_name='address',
            name='thana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userInfo.thana'),
        ),
        migrations.AlterField(
            model_name='address',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userInfo.village'),
        ),
    ]
