# Generated by Django 3.1 on 2021-04-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0013_auto_20210405_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationinfo',
            name='completeness',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='educationinfo',
            name='degree',
            field=models.IntegerField(choices=[(1, 'PRIMARY'), (2, 'SSC'), (3, 'HSC'), (4, 'BACHELOR'), (5, 'MASTERS'), (6, 'OTHERS')], null=True),
        ),
    ]
