# Generated by Django 3.1 on 2021-04-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0014_auto_20210405_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='countries',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='districts',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='division',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='postoffice',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='thana',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='title',
            new_name='name',
        ),
    ]
