# Generated by Django 3.1 on 2021-04-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0015_auto_20210405_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='countryCode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='defaultCurrency',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
