# Generated by Django 3.1 on 2021-04-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0016_auto_20210405_2331'),
        ('userInfo', '0014_auto_20210405_1921'),
    ]

    operations = [
    ]
