# Generated by Django 3.1 on 2021-04-07 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userInfo', '0019_auto_20210407_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universityName', models.CharField(blank=True, max_length=254)),
                ('degreeName', models.IntegerField(choices=[(1, 'PRIMARY'), (2, 'SSC'), (3, 'HSC'), (4, 'BACHELOR'), (5, 'MASTERS'), (6, 'OTHERS'), (7, '')], null=True)),
                ('field', models.CharField(blank=True, max_length=254)),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('currentStudent', models.BooleanField(default=False)),
                ('grade', models.FloatField(null=True)),
                ('activites', models.CharField(blank=True, max_length=254)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('completeness', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
