# Generated by Django 3.1 on 2021-04-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0020_universityinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='sameAsPresentAddress',
            field=models.BooleanField(default=False),
        ),
    ]
