# Generated by Django 3.1 on 2021-04-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0021_address_sameaspresentaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='sameAsPresentAddress',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
