# Generated by Django 3.1 on 2021-04-11 18:10

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0022_auto_20210411_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermobile',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
