# Generated by Django 3.1 on 2021-04-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0025_auto_20210414_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermobile',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
