# Generated by Django 3.1 on 2021-04-23 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0026_usermobile_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, null=True, upload_to='SchoolPics')),
                ('name', models.CharField(max_length=255)),
                ('startClass', models.IntegerField(null=True)),
                ('endClass', models.IntegerField(null=True)),
                ('establishDate', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='schoolinfo',
            name='schoolName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userInfo.school'),
        ),
    ]
