# Generated by Django 3.1 on 2021-04-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0027_auto_20210423_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='SchoolPics'),
        ),
    ]
