# Generated by Django 3.1 on 2021-04-25 09:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userInfo', '0030_auto_20210424_2126'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collegeinfo',
            unique_together={('user', 'collegeName')},
        ),
        migrations.AlterUniqueTogether(
            name='schoolinfo',
            unique_together={('user', 'schoolName')},
        ),
    ]
