# Generated by Django 3.1 on 2021-04-25 16:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0030_auto_20210424_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=254)),
                ('image', models.ImageField(blank=True, max_length=512, null=True, upload_to='universityPics')),
            ],
        ),
        migrations.RemoveField(
            model_name='universityinfo',
            name='degreeName',
        ),
        migrations.RemoveField(
            model_name='universityinfo',
            name='field',
        ),
        migrations.RemoveField(
            model_name='universityinfo',
            name='universityName',
        ),
        migrations.AddField(
            model_name='universityinfo',
            name='semester',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('university', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userInfo.university')),
            ],
        ),
        migrations.AddField(
            model_name='universityinfo',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userInfo.department'),
        ),
        migrations.AddField(
            model_name='universityinfo',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userInfo.university'),
        ),
    ]
