# Generated by Django 3.1 on 2021-04-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0031_auto_20210425_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='university',
            new_name='name',
        ),
    ]
