# Generated by Django 3.1 on 2021-04-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0031_auto_20210425_1527'),
        ('userInfo', '0032_auto_20210425_2243'),
    ]

    operations = [
    ]
