# Generated by Django 3.1 on 2021-05-12 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0033_merge_20210426_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userInfo.districts'),
        ),
        migrations.AddField(
            model_name='school',
            name='schoolNumber',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
