# Generated by Django 3.1 on 2021-02-04 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('designcontest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestdataperuser',
            name='submitTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contestdataperuser',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='designcontest',
            name='endDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='designcontest',
            name='startDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='contestdataperuser',
            unique_together={('user', 'designContest')},
        ),
        migrations.CreateModel(
            name='ContestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='designContest')),
                ('contestData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designcontest.contestdataperuser')),
            ],
        ),
        migrations.RemoveField(
            model_name='contestdataperuser',
            name='imgFile',
        ),
    ]
