# Generated by Django 3.1 on 2021-02-05 16:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('designcontest', '0002_auto_20210205_0140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContestDataPerUser',
            new_name='ContestData',
        ),
    ]
