# Generated by Django 3.1 on 2021-02-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designcontest', '0004_auto_20210211_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestdata',
            name='submitTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
