# Generated by Django 3.1 on 2021-02-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designcontest', '0005_auto_20210220_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='designcontest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='designContest'),
        ),
    ]
