# Generated by Django 3.1 on 2021-03-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designcontest', '0006_designcontest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='designcontest',
            name='reward',
            field=models.TextField(blank=True),
        ),
    ]
