# Generated by Django 3.1 on 2021-03-02 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designcontest', '0007_designcontest_reward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContestEnroll',
        ),
    ]
