# Generated by Django 3.1 on 2021-03-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designcontest', '0008_delete_contestenroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='designcontest',
            name='contestDetails',
            field=models.TextField(blank=True),
        ),
    ]
