# Generated by Django 3.1 on 2021-04-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designcontest', '0009_designcontest_contestdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestimage',
            name='side',
            field=models.CharField(default='', max_length=50),
        ),
    ]
