# Generated by Django 3.1 on 2021-01-31 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='bannerImage')),
                ('title', models.TextField(verbose_name='Give a Title')),
                ('package', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='package.package')),
            ],
        ),
    ]
